# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\"\x07\n\x05\x45mpty\"x\n\x0b\x43leanedData\x12\x0f\n\x07x_train\x18\x01 \x03(\x01\x12\x0f\n\x07y_train\x18\x02 \x03(\x01\x12\x0e\n\x06x_test\x18\x03 \x03(\x01\x12\x0e\n\x06y_test\x18\x04 \x03(\x01\x12\x13\n\x0b\x64\x61tes_train\x18\x05 \x03(\t\x12\x12\n\ndates_test\x18\x06 \x03(\t20\n\x0b\x44\x61taService\x12!\n\tCleanData\x12\x06.Empty\x1a\x0c.CleanedDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=15
  _globals['_EMPTY']._serialized_end=22
  _globals['_CLEANEDDATA']._serialized_start=24
  _globals['_CLEANEDDATA']._serialized_end=144
  _globals['_DATASERVICE']._serialized_start=146
  _globals['_DATASERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
