services:
  data-server:
    build: 
      context: ./data
      dockerfile: Dockerfile
    image: data_server
    ports:
      - "8080:8080"
    networks:
      - example-network
  
  train-server:
    build: 
      context: ./train
      dockerfile: Dockerfile
    image: train_server
    ports:
      - "8081:8081"
    networks:
      - example-network
  
  test-server:
    build: 
      context: ./testing
      dockerfile: Dockerfile
    image: test_server
    ports:
      - "8082:8082"
    networks:
      - example-network
  
  grpc-client:
    build: 
      context: ./client
    depends_on:
      - data-server
      - train-server
      - test-server
    networks:
      - example-network

networks:
  example-network:
    driver: bridge
