# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: train.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btrain.proto\x12\x05train\"0\n\x0cTrainRequest\x12\x0f\n\x07x_train\x18\x01 \x03(\x01\x12\x0f\n\x07y_train\x18\x02 \x03(\x01\"\x1e\n\rTrainResponse\x12\r\n\x05model\x18\x01 \x01(\x0c\x32J\n\x0fTrainingService\x12\x37\n\nTrainModel\x12\x13.train.TrainRequest\x1a\x14.train.TrainResponseb\x06proto3')



_TRAINREQUEST = DESCRIPTOR.message_types_by_name['TrainRequest']
_TRAINRESPONSE = DESCRIPTOR.message_types_by_name['TrainResponse']
TrainRequest = _reflection.GeneratedProtocolMessageType('TrainRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINREQUEST,
  '__module__' : 'train_pb2'
  # @@protoc_insertion_point(class_scope:train.TrainRequest)
  })
_sym_db.RegisterMessage(TrainRequest)

TrainResponse = _reflection.GeneratedProtocolMessageType('TrainResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINRESPONSE,
  '__module__' : 'train_pb2'
  # @@protoc_insertion_point(class_scope:train.TrainResponse)
  })
_sym_db.RegisterMessage(TrainResponse)

_TRAININGSERVICE = DESCRIPTOR.services_by_name['TrainingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAINREQUEST._serialized_start=22
  _TRAINREQUEST._serialized_end=70
  _TRAINRESPONSE._serialized_start=72
  _TRAINRESPONSE._serialized_end=102
  _TRAININGSERVICE._serialized_start=104
  _TRAININGSERVICE._serialized_end=178
# @@protoc_insertion_point(module_scope)
